# Banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jbank
spring.datasource.username=postgres
spring.datasource.password=4462
spring.datasource.driver-class-name=org.postgresql.Driver
# Datas e fuso
spring.jackson.date-format=dd-MM-yyyy
spring.jackson.time-zone=America/Sao_Paulo
# Cache com Caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=86400s
# Logs
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.br.com.cdb.bancodigital=DEBUG
logging.level.org.springframework.security=DEBUG
# JWT
jwt.secret=minha-chave-super-secreta-minha-chave-super-secreta
# Perfil ativo
spring.profiles.active=dev
# BrasilAPI
BrasilAPI.setEnableLog=true
BrasilAPI.setEnableCache=true
BrasilAPI.setCacheTimeMinutes=10L
# API Conversor de Moedas
api.currency.url=https://api.apilayer.com/currency_data/convert
api.currency.key=j6k9BY4OO4oXOOhLiUbdjPzfsKKcxoIZ
# API Mock da Receita Federal
api.receita.url=http://localhost:8081/api/receita/cpf/